# set base image (host OS)
FROM tensorflow/tensorflow

COPY dockerfiles/requirements.txt /tmp/

RUN set -ex; \
    pip3 --no-cache-dir install --requirement /tmp/requirements.txt

ENV PYTHONPATH "/workspaces/Recomendador/src"


ARG USERNAME=research
ARG USER_UID=777666
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME